project_id = "bqckduaygatcopxyuyyv"

[functions.send-contact-message]
verify_jwt = false

[functions.send-charter-request]
verify_jwt = false

[functions.send-charter-anfrage]
verify_jwt = false

[functions.facebook-conversion]
verify_jwt = false
