[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  PRERENDER = "1"

[[redirects]]
  from = "/reviere/mittelmeer/kroatien/kvarner-bucht"
  to = "/reviere/mittelmeer/kroatien/kvarner"
  status = 301

[[redirects]]
  from = "/reviere/mittelmeer/kroatien/norddalmatien"
  to = "/reviere/mittelmeer/kroatien/zadar"
  status = 301

[[redirects]]
  from = "/reviere/mittelmeer/kroatien/mitteldalmatien"
  to = "/reviere/mittelmeer/kroatien/dalmatien-split"
  status = 301

[[redirects]]
  from = "/reviere/mittelmeer/kroatien/sueddalmatien"
  to = "/reviere/mittelmeer/kroatien/dubrovnik"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
