// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqckduaygatcopxyuyyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxY2tkdWF5Z2F0Y29weHl1eXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDQ4MTYsImV4cCI6MjA3MjQyMDgxNn0.0B26YgIZQun2tjAj-aeQywSn-kklpgIS2CB1mpoPMv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use a safe storage to avoid iframe/localStorage security errors
const memoryStorage: Storage = {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
  clear: () => {},
  key: () => null,
  length: 0,
};

const getSafeStorage = (): Storage => {
  try {
    const ls = window.localStorage;
    const testKey = "__sb_test__";
    ls.setItem(testKey, "1");
    ls.removeItem(testKey);
    return ls;
  } catch {
    return memoryStorage;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});